# Generated by Django 5.0 on 2025-04-02 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_post_dislikes_remove_post_likes_post_dislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
