# Generated by Django 5.0 on 2025-04-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_comment_created_at_alter_dislike_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='viewed_posts',
            field=models.ManyToManyField(blank=True, related_name='viewed_by', to='main.post'),
        ),
    ]
